Multiple instances
noris-network/ansible-prometheus-kafka-adapter pull request #1
Opened 2020-10-15 13:46 UTC by brotzeit

2020-10-15 14:59 UTC, obitech commented
Are we missing the actual playbook here?

2020-10-15 18:00 UTC, brotzeit commented
Updated ;)

2020-10-16 06:37 UTC, obitech commented
> Updated ;)

I mean there are no task files, just an updated readme and tests 🤔

2020-10-16 07:01 UTC, brotzeit commented
Ja das hab ich mich auch schon gefragt. Er is leider gerade im Urlaub deswegen kann ichs dir nicht beantworten =)

2020-10-20 07:37 UTC, obitech requested changes

2020-10-20 07:37 UTC, obitech commented on tasks/configure_systemd.yml
> +- block:
Applying this block should trigger the restart handler

2020-10-20 11:17 UTC, obitech commented on tasks/configure_systemd.yml
> +- block:
We also want to restart when we change the systemd unit env file btw.

2020-10-23 08:46 UTC, merged